backend:
  name: github
  repo: DylanTackoor/wmi.io

site_url: https://wmi.io
logo_url: https://wmi.io/admin/logo.svg
publish_mode: editorial_workflow
media_folder: static/assets
public_folder: assets

collections:
  - name: posts
    label: Post
    label_singular: Posts
    description: Blog posts. TODO include guidlines here.
    folder: src/posts
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - label: 'Pages'
    name: 'pages'
    description: Pages. TODO include guidlines here.
    files:
      - label: 'About Page'
        name: 'about'
        file: 'src/cms/content/about.json'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: Photo, name: photo, widget: image }
      - label: 'Locations Page'
        name: 'locations'
        file: 'src/cms/content/locations.json'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Locations
            name: locations
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Address, name: address, widget: string }
      - label: 'Careers Page'
        name: 'careers'
        file: 'src/cms/content/careers.json'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Careers
            name: careers
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Department, name: department, widget: string }
              - label: 'Opened'
                name: 'opened'
                widget: 'date'
                default: ''
                format: 'MMM Do YY'
