backend:
  name: github
  repo: DylanTackoor/wmi.io

site_url: https://wmi.io
logo_url: https://wmi.io/admin/logo.svg
publish_mode: editorial_workflow
media_folder: static/assets
public_folder: assets

collections:
  - name: posts
    label: Post
    label_singular: Posts
    description: Blog posts. TODO include guidlines here.
    folder: src/posts
    create: true
    fields:
      - { name: path, label: Path } # TODO: change to slug
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
