backend:
  name: github
  repo: DylanTackoor/wmi.io

site_url: https://banners.wmi.io
logo_url: https://banners.wmi.io/admin/logo.svg
# publish_mode: editorial_workflow # TODO: reenable before this goes live
media_folder: static/assets
public_folder: assets
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'

collections:
  - label: Campaigns
    label_singular: Campaign
    name: campaign
    description: Zip files of banners
    editor:
      preview: false
    folder: src/banners
    create: true
    fields:
      - label: Variant
        name: variant
        widget: string
      - label: Banners
        label_singular: Banner
        name: banners
        widget: list
        fields:
          - label: Length
            name: length
            widget: number
            default: 300
            valueType: 'int'
            min: 1
            step: 1
          - label: Width
            name: width
            widget: number
            default: 300
            valueType: 'int'
            min: 1
            step: 1

  - label: Settings
    label_singular: Setting
    name: settings
    description: Various settings across the site
    editor:
      preview: false
    files:
      - label: Settings
        name: settings
        file: src/cms/content/settings/settings.json
        fields:
          - label: Worldmedia Logo
            name: wmiLogo
            widget: image
          - label: Client Logo
            name: clientLogo
            widget: image
          - label: Client URL
            name: clientURL
            widget: string
      - label: Design
        name: design
        file: src/cms/content/design.json
        fields:
          - label: Theme Color
            name: themeColor
            widget: string
          - label: Background Color
            name: backgroundColor
            widget: string
            # pattern:
            #   [
            #     '/^((0x){0,1}|#{0,1})([0-9A-F]{8}|[0-9A-F]{6})$/gi',
            #     'Hex Color',
            #   ]
