backend:
  name: github
  repo: DylanTackoor/wmi.io

site_url: https://wmi.io
logo_url: https://wmi.io/admin/logo.svg
publish_mode: editorial_workflow
media_folder: static/assets
public_folder: assets

collections:
  - name: posts
    label: Post
    label_singular: Posts
    description: Blog posts. TODO include guidlines here.
    folder: src/posts
    create: true
    fields:
      - name: slug
        label: Slug
      - name: date
        label: Date
        widget: date
      - name: title
        label: Title
      - name: body
        label: Body
        widget: markdown

  - label: 'Pages'
    name: 'pages'
    description: Pages. TODO include guidlines here.
    files:
      - label: 'About'
        name: 'about'
        file: 'src/cms/content/about.json'
        fields:
          - label: Title
            name: title
            widget: string
          - label: Intro
            name: intro
            widget: markdown
          - label: Team
            name: team
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Position
                name: position
                widget: string
              - label: Photo
                name: photo
                widget: image
      - label: 'Locations'
        name: 'locations'
        file: 'src/cms/content/locations.json'
        fields:
          - label: Title
            name: title
            widget: string
          - label: Intro
            name: intro
            widget: markdown
          - label: Locations
            name: locations
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Address
                name: address
                widget: string
      - label: 'Careers'
        name: 'careers'
        file: 'src/cms/content/careers.json'
        fields:
          - label: Title
            name: title
            widget: string
          - label: Intro
            name: intro
            widget: markdown
          - label: Departments
            name: departments
            widget: list
            fields:
              - label: Department
                name: name
                widget: string
              - label: Careers
                name: careers
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: 'Opened'
                    name: 'opened'
                    widget: 'date'
                    default: ''
                    format: 'MMM Do YY'

  - label: 'Settings'
    name: 'settings'
    description: Various settings across the site
    files:
      - label: 'Analytics'
        name: 'analytics'
        file: 'src/cms/content/analytics.json'
        fields:
          - label: 'Google Analytics Key'
            name: googleAnalyticsKey
            widget: string
      - label: 'Design'
        name: 'design'
        file: 'src/cms/content/design.json'
        fields:
          - label: 'Theme Color'
            name: themeColor
            widget: string
          - label: 'Background Color'
            name: backgroundColor
            widget: string
            # pattern:
            #   [
            #     '/^((0x){0,1}|#{0,1})([0-9A-F]{8}|[0-9A-F]{6})$/gi',
            #     'Must be a valid hex color.',
            #   ]
