/** Declaration file generated by dts-gen */

export = emotion_normalize;

declare const emotion_normalize: {
    default: {
        map: any;
        name: string;
        next: any;
        styles: string;
    };
};

